[build]
  command = "yarn build"
  publish = "dist"

[[plugins]]
  package = "/.netlify/netlify-plugin-jest"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

[[plugins]]
  package = "netlify-plugin-a11y"
    [plugins.inputs]
      checkPaths = ['/']
      resultMode = "warn"
